#
# For debugging with Log etc - 19/7/26
#

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=20
# CONFIG_THREAD_NAME=y
# CONFIG_INIT_STACKS=y

CONFIG_PRINTK=y
# OTA
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=n
