#
# Nurse_Call_SpO2 Combined Firmware Configuration
#

# nRF board library & GPIO
CONFIG_DK_LIBRARY=y
CONFIG_GPIO=y

# Generic networking options
CONFIG_NETWORKING=y

# L2 OpenThread enabling
CONFIG_COAP=y
CONFIG_NET_L2_OPENTHREAD=y
CONFIG_OPENTHREAD=y
CONFIG_OPENTHREAD_COAP=y
CONFIG_OPENTHREAD_FTD=y

# Network sockets
CONFIG_COAP_UTILS=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV6=y
CONFIG_NET_SOCKETS_POLL_MAX=4

# Same network Master Key for client and server
CONFIG_OPENTHREAD_MANUAL_START=y
CONFIG_OPENTHREAD_JOINER=y
CONFIG_OPENTHREAD_NETWORKKEY="00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff"
CONFIG_OPENTHREAD_PANID=43969

CONFIG_MBEDTLS_SHA1_C=n
CONFIG_FPU=y

# Size Optimizations
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_CBPRINTF_NANO=y

# Logging
CONFIG_LOG=n
CONFIG_OPENTHREAD_SLAAC=y

# UART & ADC
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_0_INTERRUPT_DRIVEN=y
CONFIG_ADC=y
CONFIG_USE_ADC_SENSOR=y

# NVS Flash & Reboot
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_REBOOT=y

# Stack tuning for Multithreading
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_OPENTHREAD_THREAD_STACK_SIZE=8192

CONFIG_OPENTHREAD_DEFAULT_TX_POWER=8
CONFIG_BOOTLOADER_MCUBOOT=n

# BLE Configuration
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_NUS=y
CONFIG_BT_SETTINGS=n
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_BT_DEVICE_NAME="NC_SpO2_Device"
CONFIG_BT_BUF_ACL_TX_COUNT=10
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_CONN_TX_MAX=10
CONFIG_BT_ATT_TX_COUNT=10
CONFIG_BT_ATT_PREPARE_COUNT=2

# OTA DFU
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y

# Power Management & Hibernation
CONFIG_POWEROFF=y
CONFIG_PM_DEVICE=y
CONFIG_DEVICE_PREFIX="NC_SP"
CONFIG_DEVICE_DEFAULT_PROFILE="E4A_%.8s"
