# Keeping this empty so that base module will not include it. 

# SB_CONFIG_BOOTLOADER_MCUBOOT=y
# SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
# SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="D:/TT_Codes/Arun_Keys_Tokuchu/Arun_26_key.pem"