# Device Identity
CONFIG_DEVICE_PREFIX="NC_SP"
CONFIG_BT_DEVICE_NAME="NC_SpO2_Device"

# Hardware Peripherals (Battery ADC)
CONFIG_ADC=y
CONFIG_USE_ADC_SENSOR=y

# Increased Heap for Dual-Thread Concurrent Processing
CONFIG_HEAP_MEM_POOL_SIZE=8192
